### PR TITLE
Fix connection delete and change table actions UX

### LINKED ISSUE #44: Fix connection delete and change table actions UX
- [x] Update all states related to the connections list
- [x] Add an edit column at connections table
- [x] Add loading states at query-runner

### PR DESCRIPTION
**Pull request by Matozinho**
This pull request closes #44 and includes significant refactoring and improvements to the connections management and query execution functionalities. The most important changes involve migrating state management to a custom hook, enhancing user feedback with loading states, and refactoring the connection table component to improve code readability and maintainability.

### Refactoring and State Management:

* [`src/app/(main)/connections/_components/connection-table.tsx`](diffhunk://#diff-fc821585abd5135454d3443bcc5921ff660979bb39fa87e079319ebcbca8738fR23-R79): Refactored to use `useConnectionsStore` for state management, removing local state and actions. Added loading states and error handling for connection operations. [[1]](diffhunk://#diff-fc821585abd5135454d3443bcc5921ff660979bb39fa87e079319ebcbca8738fR23-R79) [[2]](diffhunk://#diff-fc821585abd5135454d3443bcc5921ff660979bb39fa87e079319ebcbca8738fR99-R104) [[3]](diffhunk://#diff-fc821585abd5135454d3443bcc5921ff660979bb39fa87e079319ebcbca8738fR115-R130)
* [`src/hooks/use-connections.ts`](diffhunk://#diff-7e70faaed18fd476d5a39f61123c86a33712fcf2a7a349b9345d9fd0ddb128a4R1-R75): Created a custom hook `useConnectionsStore` to manage connection states and operations, including fetching, deleting, refreshing, saving, and updating connections.

### User Feedback Enhancements:

* [`src/app/(main)/connections/_components/connection-table.tsx`](diffhunk://#diff-fc821585abd5135454d3443bcc5921ff660979bb39fa87e079319ebcbca8738fR146-R154): Added `Skeleton` components to display loading states for connections.
* [`src/app/(main)/query-runner/_components/cql-editor.tsx`](diffhunk://#diff-c3d008cee84b65d82023278c89d53a325b14f0df0e41dfe05a6b97bc57e63f16R47): Added loading state for query results and used `Skeleton` components to indicate loading. [[1]](diffhunk://#diff-c3d008cee84b65d82023278c89d53a325b14f0df0e41dfe05a6b97bc57e63f16R47) [[2]](diffhunk://#diff-c3d008cee84b65d82023278c89d53a325b14f0df0e41dfe05a6b97bc57e63f16L332-R343)

### Component and Import Improvements:

* [`src/app/(main)/connections/_components/row-actions.tsx`](diffhunk://#diff-dac9fed6f9f19ac8e1f33cc4f000378458734ed7422ede1cfb9fafd788bcda65R1-R66): Created a new `RowActions` component to handle connection actions (update, refresh, delete) with user feedback.
* [`src/actions/query-keyspaces.ts`](diffhunk://#diff-a1f9a04cf79cd6866c983360bc0bd78dd58e57c14e843bd31bc8c5281d4bdea2L6-R6): Updated import to use `type` keyword for type-only imports.

### Miscellaneous Changes:

* [`src/lib/internal-db/connections.ts`](diffhunk://#diff-732f3dd0028a7e36767d25261b94a842f5ea96e86ddefc683d274a1267c4ad6eL26-R31): Commented out initial connection insertion and made `deleteConnectionById` asynchronous. [[1]](diffhunk://#diff-732f3dd0028a7e36767d25261b94a842f5ea96e86ddefc683d274a1267c4ad6eL26-R31) [[2]](diffhunk://#diff-732f3dd0028a7e36767d25261b94a842f5ea96e86ddefc683d274a1267c4ad6eL76-R76)
* [`src/app/(main)/connections/_components/modal.tsx`](diffhunk://#diff-103521702ecaedc83e97eecf1240316419142813b3a762d1aa9be813bbb20a19L84-R90): Simplified `useEffect` for opening the modal and added a loading spinner to the save button. [[1]](diffhunk://#diff-103521702ecaedc83e97eecf1240316419142813b3a762d1aa9be813bbb20a19L84-R90) [[2]](diffhunk://#diff-103521702ecaedc83e97eecf1240316419142813b3a762d1aa9be813bbb20a19L181-R185)

These changes collectively improve the codebase by enhancing user experience, improving state management, and making the components more modular and maintainable.

### CODE REVIEW

File: src/lib/internal-db/connections.ts [hunk 1]
```diff
@@ -23,12 +23,12 @@ db.exec(`
...
-    (id, name, status, host, port, username, password, dc, nodes)
-  VALUES
-    (1, 'ScyllaDB Localhost', 'Offline', 'localhost', '9042', null, null, 'local', 1)
-`);
+// db.exec(`
+//   INSERT OR IGNORE INTO connections
+//     (id, name, status, host, port, username, password, dc, nodes)
+//   VALUES
+//     (1, 'ScyllaDB Localhost', 'Offline', 'localhost', '9042', null, null, 'local', 1)
+// `);
```
Comment (DanielHe4rt) [inline src/lib/internal-db/connections.ts:31]: Regarding that: this query only runs in right after the SQLite file is generated. Usually these credentials are default for LocalHost with ScyllaDB Docker Images, that's why I maintained it there.

It was conflicting with something else?

**Review by Daniel-Boll — APPROVED** [review]

File: src/lib/internal-db/connections.ts (hunk 1 above)
Comment (Matozinho) [reply src/lib/internal-db/connections.ts:31]: This was causing the strange behavior on deleting that @Daniel-Boll had mentioned earlier because when you delete this from db, it just adds again when the file is re-executed.

We may keep it and find a way to avoid this specific entry from being deleted.

**Review by gvieira18 — APPROVED** [review]

**Review by DanielHe4rt — APPROVED** [review]
